/*10/24/24 This is the final group of changes that I'll be making for this course. For this reason, I will be 
 * focusing on polishing the Application and getting any features cleaned up.  I suspect this will take about 4 more 
 * hours of work.
 * 
 * 10/27/2024 Completed the final changes to my project. It took a total of about 5 hours, as I continued defining
 * the style with my spouse, who was my acting client through this project. I also added some editing options for the
 * user and verified that information would carry over from form to form.  
 * 
 * These are the changes I made:
 * updated the style of all of the boxes
 * added an edit page
 * added masking within the forms that took information
 * fixed a bug I found that was causing the medical conditions to update of all users, not just a newly entered user
 * verified consistent font and border styles throughout
 * removed the image checkboxes, they turned out to be unnecessary 
 * focused on generating a simple user interface to address the clients that will be utilizing the scheduling tools
 * 
 * 
 */

//import libraries
using System;
using System.IO;
using System.Windows.Forms;
namespace WindowsFormsApp1
{
    partial class Form1
    {

        private System.ComponentModel.IContainer components = null;

        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

 //component initilization generated by the framework
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.label1 = new System.Windows.Forms.Label();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.toolTip2 = new System.Windows.Forms.ToolTip(this.components);
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 22.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(423, 40);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.MinimumSize = new System.Drawing.Size(20, 20);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(259, 42);
            this.label1.TabIndex = 0;
            this.label1.Text = "Sign Up Form";
            this.label1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.label1.Click += new System.EventHandler(this.label1_Click);
            // 
            // textBox3
            // 
            this.textBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.textBox3.Location = new System.Drawing.Point(587, 209);
            this.textBox3.Margin = new System.Windows.Forms.Padding(4);
            this.textBox3.Multiline = true;
            this.textBox3.Name = "textBox3";
            this.textBox3.ReadOnly = true;
            this.textBox3.Size = new System.Drawing.Size(393, 184);
            this.textBox3.TabIndex = 16;
            this.textBox3.TextChanged += new System.EventHandler(this.textBox3_TextChanged);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(676, 144);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(196, 25);
            this.label6.TabIndex = 17;
            this.label6.Text = "Medical Conditions";
            // 
            // button2
            // 
            this.button2.AutoSize = true;
            this.button2.BackColor = System.Drawing.Color.OrangeRed;
            this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button2.Location = new System.Drawing.Point(824, 23);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(92, 59);
            this.button2.TabIndex = 25;
            this.button2.Text = "Logout";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(99, 424);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(156, 46);
            this.button3.TabIndex = 27;
            this.button3.Text = "Go to Calendar";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.Location = new System.Drawing.Point(587, 424);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(128, 42);
            this.button4.TabIndex = 28;
            this.button4.Text = "Edit your information";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // textBox1
            // 
            this.textBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.textBox1.Location = new System.Drawing.Point(99, 209);
            this.textBox1.Margin = new System.Windows.Forms.Padding(4);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new System.Drawing.Size(393, 184);
            this.textBox1.TabIndex = 29;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft YaHei", 13.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.label5.Location = new System.Drawing.Point(133, 138);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(151, 31);
            this.label5.TabIndex = 31;
            this.label5.Text = "Your Events";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft YaHei", 13.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Black;
            this.label3.Location = new System.Drawing.Point(560, 78);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(0, 31);
            this.label3.TabIndex = 36;
            this.label3.Click += new System.EventHandler(this.label3_Click_1);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.Color.PaleTurquoise;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.ClientSize = new System.Drawing.Size(1055, 524);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.textBox3);
            this.Controls.Add(this.label1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Adaptive Recreation Events";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private void Form1_Load(object sender, EventArgs e)
        {
 
        }

        private void label2_Click_1(object sender, EventArgs e)
        {

        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {

        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {
 
        }

        //commented items (images) were intentionally left for the sake of potential use in the future
        private void checkBox4_CheckedChanged(object sender, EventArgs e)
        {
            String path;
     /*       if (checkBox4.Checked)
            {
                path = Directory.GetCurrentDirectory();
                string imagePath = Path.Combine(path, "Driving.jpg");
             //   pictureBox4.ImageLocation = imagePath;
             //   pictureBox4.SizeMode = PictureBoxSizeMode.AutoSize;

             //   pictureBox4.Show();
            }
            else
            {
             //   pictureBox4.Hide();
            } */
        }

        private void checkBox3_CheckedChanged(object sender, EventArgs e)
        {
            String path;
      /*      if (checkBox3.Checked)
            {
                path = Directory.GetCurrentDirectory();
                string imagePath = Path.Combine(path, "Video games.jpg");
              //  pictureBox3.ImageLocation = imagePath;
              //  pictureBox3.SizeMode = PictureBoxSizeMode.AutoSize;

              //  pictureBox3.Show();
            }
            else
            {
              //  pictureBox3.Hide();
            }
      */
        }

        private void checkBox2_CheckedChanged(object sender, EventArgs e)
        {
            String path;
         /*   if (checkBox2.Checked)
            {
                path = Directory.GetCurrentDirectory();
                string imagePath = Path.Combine(path, "volleyball.jpg");
               // pictureBox2.ImageLocation = imagePath;
               // pictureBox2.SizeMode = PictureBoxSizeMode.AutoSize;

               // pictureBox2.Show();
            }
            else
            {
               // pictureBox2.Hide();
            }*/
        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            String path;
         /*   if (checkBox1.Checked)
            {
                path = Directory.GetCurrentDirectory();
                string imagePath = Path.Combine(path, "paddleboarding.jpg");
              //  pictureBox1.ImageLocation = imagePath;
              //  pictureBox1.SizeMode = PictureBoxSizeMode.AutoSize;

              //  pictureBox1.Show();
            }
            else
            {
              //  pictureBox1.Hide();
            } */
        }

        private void button1_Click(object sender, EventArgs e)
        {
       
        }

        private void label1_Click(object sender, EventArgs e)
        {
   
        }

        private void label4_Click(object sender, EventArgs e)
        {
      
        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ToolTip toolTip2;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private Button button4;
        private TextBox textBox1;
        private Label label5;
        //I had to make this label public to update it for username validation on the events page
        public System.Windows.Forms.Label label3;
    }
}

